# Spring config
spring:
  devtools:
    add-properties: true
    livereload:
      enabled: true #default
      port: 35729 #default
  thymeleaf:
    cache: false
  web:
    resources:
      chain:
        cache: false
  datasource:
    name: DevDB
    url: jdbc:h2:mem:DevDB
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create}
    show-sql: true

# App Initialization property
app:
  db:
    initialize: true
    populate:
      enabled: true
      links:
        count: 24

# File storage configuration
storage:
  type: ${STORAGE_TYPE:system}

# Security / authentication
auth:
  initialPass: ${INITIAL_ADMIN_PASS:admin}

# Logging
logging:
  level:
    web: DEBUG

# Server
server:
  servlet:
    session:
      cookie:
        secure: false

# Management endpoints
management:
  endpoints:
    jmx:
      exposure:
        exclude: null
    web:
      exposure:
        include: "*"

# Swagger / SpringDoc
springdoc:
  api-docs:
    enabled: true