# Application server settings
server:
  port: 8081
  # Disable the default Whitelabel error page
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      cookie:
        http-only: true
        secure: true

# Spring Global Configs
spring:
  threads:
    virtual:
      enabled: true
  thymeleaf:
    encoding: UTF-8
  devtools:
    add-properties: false
    livereload:
      enabled: false
  jpa:
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: true # needed for auto-detection
    # needs to be true as we use entity access inside thymeleaf that need db conn due to lazy init
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# File storage configuration
storage:
  location: ./uploads
  type: ${STORAGE_TYPE}
  key: ${STORAGE_KEY}
  secret: ${STORAGE_SECRET}

# Security / authentication
auth:
  key: ${SERVER_KEY}
  salt: ${SERVER_SALT}
  initialPass: ${INITIAL_ADMIN_PASS}

# Management endpoints
management:
  endpoints:
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: health

# Swagger / SpringDoc
springdoc:
  api-docs:
    enabled: false